### ISSUE TITLE
Compatability for 6.x.

### ISSUE THREAD

**Issue by groverjatin17** [nabilbendafi/country-flag-fieldformatters#2]
I have a use case where this plugin can be used. 
Does anyone know if it will be developed to be compatibile  with Kibana 6.x and onwards?

**Comment by nabilbendafi** [comment]
Plugin has been updated and tested with Kibana 6.6.0 in [v1.2.0](https://github.com/nabilbendafi/country-flag-fieldformatters/releases/tag/v1.2.0).

**Comment by nabilbendafi** [comment]
Closing the issue.
